version: '3'
services:
  app:
    image: csnguyen/ehr-chatbot
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - 8000:8000
    volumes:
    - app-data:/workspace/data
volumes:
  app-data: